<!-- app/code/Vendor/Module/view/frontend/templates/landing_form.phtml -->

<?php
/** @var LandingPage\Form\Block\Index $block */
?>
<div class="landing-page-content">
    <?php
    if ($customerName = $block->getCustomerName()) {
        $customerEmail = $block->getCustomerEmail();
    }
    ?>

    <?php if ($customerName) { ?>

        <fieldset class="fieldset">
            <legend class="legend"><span>Contact Information</span></legend>
            <br>

            <input type="hidden" name="error_url" value="">

            <div class="field required">
                <label class="label" for="name">
                    <span>Name</span>
                </label>
                <div class="control">
                    <input type="text" id="name" name="name" value="<?= $block->escapeHtml($customerName) ?>"
                        title="Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true" disabled>
                </div>
            </div>

            <div class="field required">
                <label for="email" class="label">
                    <span>Email</span>
                </label>
                <div class="control">
                    <input type="email" name="email" id="email" value="<?= $block->escapeHtml($customerEmail) ?>"
                        title="Email" class="input-text" disabled>
                </div>
            </div>

            <div class="field">
                <label for="telephone" class="label">
                    <span>Comment</span>
                </label>
                <div class="control">
                    <textarea type="tel" name="telephone" id="telephone" class="input-textarea"></textarea>
                </div>
            </div>

            <div style="margin-bottom:.5rem;">
                <button type="submit" title="Add to Cart" class="action tocart primary">
                    <span>Add to Cart</span>
                </button>
            </div>

            <div>
                <button style="background-color: #00B05A;" type="submit" title="Read More" class="action tocart primary">
                    <span>Read More</span>
                </button>
            </div>
        </fieldset>

    <?php } else { ?>

        <h1 style="font-size:5rem;">Sign In to Continue</h1>

    <?php } ?>
</div>
